### ISSUE TITLE
groqit with `num_chips=8` can give much worse performance than non-multichip

### ISSUE THREAD

**Issue by ecpeterson** [groq/groqflow#2]
## Problem

When increasing `groq-compiler`'s supply of GroqChips, it yields much worse compilation results for models + workloads which don't exhibit simple data parallelism.

## Example

Here's some code, adapted from https://github.com/groq/groqflow/blob/main/examples/pytorch/estimate_performance.py :

```python
import torch
from groqflow import groqit

torch.manual_seed(0)

# Define model class
class SmallModel(torch.nn.Module):
    def __init__(self, in_channels, out_channels, kernel_edge):
        super(SmallModel, self).__init__()
        self.conv3d = torch.nn.Conv3d(in_channels, out_channels, kernel_size=[kernel_edge,kernel_edge,kernel_edge])

    def forward(self, x):
        output = self.conv3d(x)
        return output


# Instantiate model and generate inputs
batch_size = 1
in_channels = 5
out_channels = 50
cube_edge = 17
kernel_edge = 3

pytorch_model = SmallModel(in_channels, out_channels, kernel_edge)
inputs = {"x": torch.rand([batch_size, in_channels, cube_edge, cube_edge, cube_edge])}

# Build model
gmodel = groqit(pytorch_model, inputs, groqview=True)

# Get performance estimates in terms of latency and throughput
estimate = gmodel.estimate_performance()
print("Your build's estimated performance is:")
print(f"{estimate.latency:.7f} {estimate.latency_units}")
print(f"{estimate.throughput:.1f} {estimate.throughput_units}")
```

This runs fine and reports 14451.4 inferences per second. If you add `num_chips=8` to the `groqit` call, it drops to 92.2 IPS. Since it's still possible to host the entire model on one of the chips, I would expect `groq-compiler` to yield results which are at least as good as the single-chip case.

**Note:** If I use the `estimate_performance.py` example verbatim, with its single fully-connected layer, then the multichip `groq-compile` call fails because there are too few nodes for it to disperse. The `Conv3d` in the example above is only meant to give it enough "meat".

## Versions
+ `groqflow`: 2.1.1
+ `groq-devtools`: 0.9.0
+ `groq-runtime:: 0.9.0
+ Ubuntu 22.04

**Comment by vgodsoe-groq** [comment]
Hello, 

Thank you for your feedback. You are correct, **currently**, single-chip compiles are more optimized than multi-chip compiles. As we continue to mature our compiler, we expect multi-chip performance to significantly surpass single-chip performance in certain contexts. Multi-chip is primarily there today to help large models fit. Users today will get the best results by minimizing their chip counts, as off-chip incurs some latency. 

Please let me know if you have any more questions or would like to discuss further with Groq. 

Thanks,
Victoria
